### ISSUE TITLE
Problem marked in eclipse by Arr

### ISSUE THREAD

**Issue by c0der1337** [brendano/myutil#1]
When I use your LBFGS Class, I got an error marked in eclipse at each Arr.  Do you know how I could fix it? 
Here is an example:
static double vecdot(double[] a, double[] b, int n) {
        return Arr.innerProduct(a, b);
    }
Thanks in advance

**Comment by brendano** [comment]
It should be in there: https://github.com/brendano/myutil/blob/master/src/util/Arr.java
